# Generated by Django 5.1.5 on 2025-01-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_category_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
